# Generated by Django 5.2.15 on 2026-06-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='base_rate',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='هزینه ورودی (تومان)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='هزینه هر ساعت اضافه (تومان)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال؟'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام تعرفه (نوع خودرو)'),
        ),
        migrations.AlterField(
            model_name='vehicletraffic',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ورود'),
        ),
        migrations.AlterField(
            model_name='vehicletraffic',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AlterField(
            model_name='vehicletraffic',
            name='is_inside',
            field=models.BooleanField(default=True, verbose_name='داخل پارکینگ است؟'),
        ),
        migrations.AlterField(
            model_name='vehicletraffic',
            name='plate_number',
            field=models.CharField(max_length=50, verbose_name='پلاک خودرو'),
        ),
        migrations.AlterField(
            model_name='vehicletraffic',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking_api.tariff', verbose_name='تعرفه اعمال شده'),
        ),
        migrations.AlterField(
            model_name='vehicletraffic',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه نهایی'),
        ),
    ]
