# Generated by Django 5.2.15 on 2026-06-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_api', '0002_alter_tariff_base_rate_alter_tariff_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('available', 'آزاد'), ('occupied', 'اشغال'), ('reserved', 'رزرو'), ('disabled', 'غیرفعال')], default='available', max_length=20)),
                ('floor', models.IntegerField(default=0)),
            ],
        ),
    ]
