# Generated by Django 5.2.15 on 2026-06-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_api', '0003_parkingspot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name_fallback', models.CharField(default='اپراتور سیستم', max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'پایان یافته')], default='active', max_length=15)),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('vehicles_entered', models.IntegerField(default=0)),
                ('vehicles_exited', models.IntegerField(default=0)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
