# Generated by Django 5.2.15 on 2026-06-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletraffic',
            name='parking_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_sessions', to='parking_api.parkingspot', verbose_name='جایگاه پارکینگ'),
        ),
    ]
